### ISSUE TITLE
小建议

### ISSUE THREAD

**Issue by wwj718** [CodeLabClub/scratch3_knn_install#3]
建议放出积木预览与一些小案例，可以参考[ml2scratch](https://github.com/champierre/ml2scratch)

**Comment by mickwubs97** [comment]
抱歉今天晚上才看到您的建议。已经做好一个GIF了，但是上传出了问题，好像是文件较大，不能一次传上来（155MB>25MB），……我计划把训练和检测分开明天再试一下。我准备添加一个是石头剪刀布的gif和识别一些其他日常物品的gif，以及简短的说明，应该能在这周末完成。

**Comment by wwj718** [comment]
@doNotBeTooSerious  太棒啦👍 ，最好是外部视频链接呢，视频放在七牛云/youtube/b站之类的地方。 放在仓库里的话，其他人git clone会比较大
